// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7TyYWtfkfUSy5B9j5FzVGgY8bHLjxw4',
    appId: '1:923624442012:android:4388d83388c31b05198559',
    messagingSenderId: '923624442012',
    projectId: 'e-book-8ba5f',
    storageBucket: 'e-book-8ba5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAU3uPL3gRdnbS2fUFIPkmZ4w62CyKzwg',
    appId: '1:923624442012:ios:d7d6420f043eba2b198559',
    messagingSenderId: '923624442012',
    projectId: 'e-book-8ba5f',
    storageBucket: 'e-book-8ba5f.appspot.com',
    androidClientId: '923624442012-0k7gt4fndvg7l7sco4im7hk7rqgdrnf0.apps.googleusercontent.com',
    iosClientId: '923624442012-ml04lb6r2sa3rltpoipcmnl52u38bll1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBookApp',
  );
}
