import 'package:get/get.dart';

class Langs extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'new books': 'News book',
          'explore': 'Explore',
          'category': 'Category',
          'login': 'Login',
          'Store': 'Store',
          'Library': 'Library',
          'Setting': 'Setting',
          'search': 'Search',
          'searching book': 'Searching book....',
          'Favorate': 'Favorate',
          'Downloaded': 'Downloaded',
          'About this book': 'About this book',
          'Read': 'Read',
          'Like this book': 'Like this book',
          'Don\'t like this book': 'Don\'t like this book',
          'Download': 'Download',
          'Remove download': 'Remove download',
          'system': 'System',
          'light': 'Light',
          'dark': 'Dark',
          'Theme': 'Theme',
          'Log out': 'Log out',
          'Cancel': 'Cancel',
          'Select theme': 'Select theme',
          'Empty': 'Empty',
          'Rating and reviews': 'Rating and review',
          'Your Review': 'Your Review',
          'No review': 'No review',
          'Review': 'Review',
          'Submit': 'Submit',
          'Sort by': 'Sort by',
          'Date': 'Date',
          'Name': 'Name',
          'Default': 'Default',
          'Success': 'Success',
          'Delete': 'Delete',
          'Edit': 'Edit',
          'Downloading': 'Downloading',
          'Write your review': 'Write your review',
        },
        'vi_VN': {
          'new books': 'Sách mới',
          'explore': 'Khám phá',
          'category': 'Danh mục',
          'login': 'Đăng nhập',
          'Store': 'Cửa hàng',
          'Library': 'Thư viện',
          'Setting': 'Cài đặt',
          'search': 'Tìm kiếm',
          'searching book': 'Tìm kiếm sách...',
          'Favorate': 'Yêu thích',
          'Downloaded': 'Đã tải xuống',
          'About this book': 'Thông tin sách',
          'Read': 'Đọc',
          'Like this book': 'Thích sách',
          'Don\'t like this book': 'Bỏ thích sách',
          'Download': 'Tải xuống',
          'Remove download': 'Xoá tải xuống',
          'system': 'Hệ thống',
          'light': 'Sáng',
          'dark': 'Tối',
          'Theme': 'Chủ đề',
          'Log out': 'Đăng xuất',
          'Cancel': 'Huỷ',
          'Select theme': 'Chọn chủ đề',
          'Empty': 'Rỗng',
          'Rating and reviews': 'Đánh giá',
          'Your Review': 'Đánh giá của bạn',
          'No review': 'Không có đánh giá',
          'Review': 'Đánh giá',
          'Submit': 'Xác nhận',
          'Sort by': 'Xắp xếp theo',
          'Date': 'Ngày',
          'Name': 'Tên',
          'Default': 'Mặc định',
          'Success': 'Thành công',
          'Delete': 'Xoá',
          'Edit': 'Chỉnh sửa',
          'Downloading': 'Đang tải',
          'Write your review': 'Viết đánh giá',
        }
      };
}
