import 'package:get/get.dart';

class Langs extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'new books': 'News book',
          'explore': 'Explore',
          'category': 'Category',
          'login': 'Login',
          'Store': 'Store',
          'Library': 'Library',
          'Setting': 'Setting',
          'search': 'Search',
          'searching book': 'Searching book....',
          'Favorate': 'Favorate',
          'Downloaded': 'Downloaded',
          'About this book': 'About this book',
          'Read': 'Read',
          'Like this book': 'Like this book',
          'Don\'t like this book': 'Don\'t like this book',
          'Download': 'Download',
          'Remove download': 'Remove download',
          'system': 'System',
          'light': 'Light',
          'dark': 'Dark',
          'Theme': 'Theme',
          'Log out': 'Log out',
          'Cancel': 'Cancel',
          'Select theme': 'Select theme',
          'Empty': 'Empty',
          'Rating and reviews': 'Rating and review',
          'Your Review': 'Your Review',
          'No review': 'No review',
          'Review': 'Review',
          'Submit': 'Submit',
          'Sort by': 'Sort by',
          'Date': 'Date',
          'Name': 'Name',
          'Default': 'Default',
          'Success': 'Success',
          'Delete': 'Delete',
          'Edit': 'Edit',
          'Downloading': 'Downloading',
          'Write your review': 'Write your review',
          'Can\'t connect': 'Can\'t connect',
          'Account disabled': 'Account disabled',
          'User not found': 'User not found',
          'Invalid email': 'Invalid email',
          'Weak password': 'Weak password',
          'Email already in use': 'Email already in use',
          'Error': 'Error',
          'Pleace write Email': 'Pleace write Email',
          'Pleace write password': 'Pleace write password',
          'Pleace write repassword': 'Pleace write repassword',
          'Can\'t sign in': 'Can\'t sign in',
          'Forget password': 'Forget password',
          'Check your mail box': 'Check your mail box',
          'Password and repasssword don\'t correct':
              'Password and repasssword don\'t correct',
          'Welcome to EBOOK': 'Welcome to EBOOK',
          'Password': 'Password',
          'Login': 'Login',
          'Sign in with Google': 'Sign in with Google',
          'Sign up': 'Sign up',
          'Repassword': 'Repassword',
          'Book': 'Book',
          'Category': 'Category',
          'Book manager': 'Book manager',
          'Category manager': 'Category manager',
          'Quatity': 'Quatity',
          'Progress': 'Progress',
          'Select image': 'Select image',
          'User information': 'User information',
          'Storage manager': 'Storage manager',
        },
        'vi_VN': {
          'new books': 'Sách mới',
          'explore': 'Khám phá',
          'category': 'Danh mục',
          'login': 'Đăng nhập',
          'Store': 'Cửa hàng',
          'Library': 'Thư viện',
          'Setting': 'Cài đặt',
          'search': 'Tìm kiếm',
          'searching book': 'Tìm kiếm sách...',
          'Favorate': 'Yêu thích',
          'Downloaded': 'Đã tải xuống',
          'About this book': 'Thông tin sách',
          'Read': 'Đọc',
          'Like this book': 'Thích sách',
          'Don\'t like this book': 'Bỏ thích sách',
          'Download': 'Tải xuống',
          'Remove download': 'Xoá tải xuống',
          'system': 'Hệ thống',
          'light': 'Sáng',
          'dark': 'Tối',
          'Theme': 'Chủ đề',
          'Log out': 'Đăng xuất',
          'Cancel': 'Huỷ',
          'Select theme': 'Chọn chủ đề',
          'Empty': 'Rỗng',
          'Rating and reviews': 'Đánh giá',
          'Your Review': 'Đánh giá của bạn',
          'No review': 'Không có đánh giá',
          'Review': 'Đánh giá',
          'Submit': 'Xác nhận',
          'Sort by': 'Xắp xếp theo',
          'Date': 'Ngày',
          'Name': 'Tên',
          'Default': 'Mặc định',
          'Success': 'Thành công',
          'Delete': 'Xoá',
          'Edit': 'Chỉnh sửa',
          'Downloading': 'Đang tải',
          'Write your review': 'Viết đánh giá',
          'Can\'t connect': 'Không thể kết nối',
          'Account disabled': 'Tài khoản không khả dụng',
          'User not found': 'Không tìm thấy tài khoản',
          'Invalid email': 'Email không chính sách',
          'Weak password': 'Mật khẩu yếu',
          'Email already in use': 'Email đã đươc sử dụng',
          'Error': 'Lỗi',
          'Pleace write Email': 'Hãy nhập Email',
          'Pleace write password': 'Hãy nhập mật khẩu',
          'Pleace write repassword': 'Hãy nhập lại mật khẩu',
          'Can\'t sign in': 'Không thể đăng nhập',
          'Forget password': 'Quên mật khẩu',
          'Check your mail box': 'Kiểm tra họp thư của bạn',
          'Password and repasssword don\'t correct': 'Mật khẩu không khớp',
          'Welcome to EBOOK': 'Chào mừng tới EBOOK',
          'Password': 'Mật khẩu',
          'Login': 'Đăng nhập',
          'Sign in with Google': 'Đăng nhập với Google',
          'Sign up': 'Đăng ký',
          'Repassword': 'Nhập lại mật khẩu',
          'Book': 'Sách',
          'Category': 'Danh mục',
          'Book manager': 'Quản lý sách',
          'Category manager': 'Quản lý danh mục',
          'Quatity': 'Số lượng',
          'Progress': 'Tiến trình',
          'Select image': 'Chọn ảnh',
          'User information': 'Thông tin người dùng',
          'Storage manager': 'Quản lý bộ nhớ',
        }
      };
}
